---
title: "Postprocessing data cleaning"
author: "nuanjun zhao"
date: "11/18/2019"
output: html_document
---

```{r}
train_set<-read.csv("../data/train_set.csv")
test_set<-read.csv("../data/test_set.csv")
train_split<-split(train_set,train_set$userId)
test_split<-split(test_set,test_set$userId)
q<-read.csv("../output/q_matrix_A2_final.csv")
q<-as.matrix(q[,-1])
q<-t(q)
dim(q)
movie<-read.csv("../output/movie_indexes.csv")
movie<-movie[,-1]
dim(train_set)
```

```{r}
new_q_split<-list()
for (k in 1:length(train_split)){
  new<-c()
for (i in 1:dim(train_split[[k]])[1]){
 new<-cbind(new,q[,which(movie==train_split[[k]]$movieId[i])])
}
  new_q_split[[k]]<-new
}
normal<-function(a){
  return(a/sqrt(sum(a^2)))
}
x_split<-list()
for (k in 1:length(train_split)){
 x_split[[k]]<-apply(new_q_split[[k]],2,normal)
}
data_split<-list()
for (k in 1:length(train_split)){
  data_split[[k]]<-cbind(train_split[[k]]$rating,t(x_split[[k]]))
}
save(data_split,file = "../output/data_split.RData")

```

```{r}
new_q_split1<-list()
for (k in 1:length(test_split)){
  new1<-c()
for (i in 1:dim(test_split[[k]])[1]){
 new1<-cbind(new1,q[,which(movie==test_split[[k]]$movieId[i])])
}
  new_q_split1[[k]]<-new1
}
x_split1<-list()
for (k in 1:length(test_split)){
 x_split1[[k]]<-apply(new_q_split1[[k]],2,normal)
}
data_split_test<-list()
for (k in 1:length(test_split)){
  data_split_test[[k]]<-cbind(test_split[[k]]$rating,t(x_split1[[k]]))
}
big_user_id<-c()
for (k in 1:length(train_split)){
if(dim(data_split[[k]])[1]>800){
 big_user_id <-c(big_user_id,k)}
}
save(data_split_test,file = "../output/data_split_test.RData")
data_split_test_big<-data_split_test[big_user_id]
data_split_test_small<-data_split_test[-big_user_id]
save(data_split_test_big,file = "../output/data_split_test_big.RData")
save(data_split_test_small,file = "../output/data_split_test_small.RData")
```

```{r}
data_split_big<-data_split[big_user_id]
data_split_small<-data_split[-big_user_id]
save(data_split_big,file = "../output/data_split_big.RData")
save(data_split_small,file = "../output/data_split_small.RData")
```

