---
title: "KRR"
output: html_document
---

```{r packages}
install.packages("remotes")
remotes::install_github("TimothyKBook/krr")

library(krr)
library(dplyr)
library(caret)
```

```{r MAIN FUNCTION}
cv.krr <- function(data, kfold, lam){
  
  set.seed(123)
  
  data.x <- as.matrix(data[,-1])
  data.y <- data[,1]
  
  n <- nrow(data.x)
  cv.id <- createFolds(1:n, k = kfold)
  
  cv.tuning <- c()
  
  for (j in cv.id){
    
    #Split Data in train and validation sets
    x.train.cv <- data.x[-j,]
    y.train.cv <- data.y[-j]
    
    x.validation.cv <- data.x[j,]
    y.validation.cv <- data.y[j]
    
    #Run Model
    mod.cv <- krr(x = x.train.cv,  y.train.cv, lambda = lam)
    
    #Estimate predictin of validation test
    pred.cv <- predict(mod.cv, x.validation.cv)
    
    #Calculate RMSE
    rmse.cv <- sqrt(mean((y.validation.cv - pred.cv)^2))
    cv.tuning <- cbind(cv.tuning, rmse.cv)
    cv.mean <- mean(cv.tuning)
    }
  
  return(cv.mean)
}
```

```{r TUNE LAMBDA}
load("../output/data_split.RData")
load("../output/data_split_small.RData")

lambdas <- c(0.4, 0.5, 0.6)

mse <- c()

for (x in lambdas){
  m <- lapply(data_split, cv.krr, 5, x)
  mse <- cbind(mse, sum(unlist(m)))
}
```

```{r PREDICT FUNCTION TRAIN}
krr.pred.train <- function(data, bestlam){
  
  #Split predictors and outcome
  data.x <- as.matrix(data[,-1])
  data.y <- data[,1]
  
  #Run Mode
  mod <- krr(x = data.x,  y = data.y, lambda = bestlam)
  
  #Extracted predicted outcome
  pred <- mod$pred
  
  return(pred)
}
```

```{r RUN FUNCTION TRAIN}
sel <- function(data){
  return(data[,1])
}

rating.krr.train <- unlist(lapply(data_split, krr.pred.train, 0.5))
rating.true <- unlist(lapply(data_split, sel))
sqrt(mean((rating.true - rating.krr.train)^2))
```

```{r PREDICT FUNCTION TEST}
krr.pred.test <- function(data.train, data.test, bestlam){
  
  #Split predictors and outcome
  data.x <- as.matrix(data.train[,-1])
  data.y <- data.train[,1]
  
  data.test.x <- as.matrix(data.test[,-1])
  
  #Run Mode
  mod <- krr(x = data.x,  y = data.y, lambda = bestlam)
  
  #Extracted predicted outcome
  pred <- predict(mod, data.test.x)
  
  return(pred)
}

```

```{r}
rating.krr.test <- unlist(lapply(data_split, krr.pred.test, 0.5))
sqrt(mean((rating.true - rating.krr.test)^2))
```




```{r WEIGHTED AVERAGE}
weights <- c(0.1, 0.9)

rmse <- c()
for (w in weights){
  rating.weighted <- rating.sda(1-w) + rating.krr(w)
  r <- sqrt(mean((y.true - rating.weighted)^2))
  rmse <- rbind(rmse, r)
}

```



